language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

install:
  - npm install
  - npm install -g
  - npm install istanbul coveralls codeclimate-test-reporter codecov.io

script:
  - tf-connected
  - tf-connected list

after_script:
  - node ./node_modules/.bin/istanbul --include-all-sources cover command.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
  - cat ./coverage/coverage.json | ./node_modules/.bin/codecov.io
