language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

before_install:
  - npm install -g npm

install:
  - npm install
  - npm install -g

script:
  - ./command.js
  - tf-commander

after_success:
  - ./node_modules/.bin/istanbul cover command.js
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info

matrix:
  ollow_failures:
    - node_js: "0.10"
    - node_js: "0.11"
    - node_js: "iojs-v1.0.4"
