language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.9"
  - "0.8"
  - "0.7"
  - "0.6"
  - "0.5"
  - "0.4"
  - "0.3"
  - "0.2"
  - "0.1"
  - "iojs"
  - "iojs-v1.0.4"

script:
  - ./command.js

after_success:
  - ./node_modules/.bin/istanbul cover command.js
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
  
matrix:
  ollow_failures:
    - node_js: "0.1"
    - node_js: "0.2"
    - node_js: "0.3"
    - node_js: "0.4"
    - node_js: "0.5"
    - node_js: "0.6"
    - node_js: "0.7"
    - node_js: "0.8"
    - node_js: "0.9"
