language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

install:
  - npm install -g
  - npm install istanbul coveralls

script:
  - tf-connected
  - tf-connected list
  
after_script:
  - node ./node_modules/.bin/istanbul --include-all-sources cover command.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
