language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.8.4"
  - "iojs-v2.5.0"

before_install:
  - npm install -g npm

install:
  - npm install
  - npm install -g

script:
  - ./command.js
  - tf-connected
