language: node_js
install:
  - npm install
  - npm install -g
  - npm update istanbul coveralls codeclimate-test-reporter codecov.io codacy-coverage
script:
  - npm test
  - tf-connected
  - tf-connected --advanced
  - tf-connected --help
after_script:
  - ./node_modules/.bin/istanbul --include-all-sources cover ./bin/command.js
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
cache:
  directories:
    - node_modules
matrix:
  include:
    - node_js: "stable"
    - node_js: "4"
    - node_js: "0.12"
