os:
  - osx
  - linux
language: node_js
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
install:
  - npm install
  - npm install -g
script:
  - npm run lint
  - npm test
  - tf-connected
  - tf-connected --advanced
  - tf-connected --help
after_script:
  - npm run istanbul
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
